ARG HA_VERSION
FROM haproxy:${HA_VERSION}

USER root
RUN mkdir -p /var/lib/haproxy/
RUN apt-get update && apt-get install -y bc certbot cron vim supervisor

COPY ./le-renew-haproxy /usr/local/sbin/le-renew-haproxy
RUN chmod +x /usr/local/sbin/le-renew-haproxy
COPY ./haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY ./cert-list.cfg /etc/haproxy/cert-list.cfg

# cron 設定定期自動更新
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
RUN echo '0 5 * * 0 root /usr/local/sbin/le-renew-haproxy >> /var/log/cron.log 2>&1' >> /etc/cron.d/cron-update-cert
RUN chmod +x /etc/cron.d/cron-update-cert
RUN touch /var/log/cron.log

# tail 為了避免container完成退出
# CMD haproxy -f /usr/local/etc/haproxy/haproxy.cfg && cron && tail -f /var/log/cron.log
# 改成 supervisor 多進程單行CMD會出問題，有LOG卻沒更新
RUN mkdir /var/log/supervisord /var/run/supervisord
COPY supervisord.conf /supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
